### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by caseyg** [opengovfoundation/opengovfoundation-theme#3]
General
- [ ] rough edges everywhere (was focused on implementing structure across the site, before finessing aspects of each page)

Header
- [x] link donate to paypal 
- [x] background image on header not body?
- [ ] nav active states aren't quite in parity w/ mockups

Footer
- [x] margins
- [x] icon height

Contact
- [x] get involved link
- [x] missing green dot on map
- [x] add red dot on directions

Home
- [x] missing correct icon for blog tout
- [x] link latest blog entry
- [x] test mailchimp form
- [x] get involved link
- [x] pull projects from CMS

About
- [x] pull person pages from CMS
- [x] finish modal implementation

News
- [ ] pagination
- [ ] single entries

Mobile/Responsive Sanity-Check
- [x] test/refine all layouts
  - [x] home
  - [x] about
    - [x] about single
  - [x] news
    - [x] news single
  - [x] projects
    - [x] project single
  - [x] contact
  - [x] catchall single (old one-off pages)
